const DATA_SCHEMA = {
  Korean: 0,
  English: 1,
  PartofSpeech: 2,
  SemanticTags: 3,
  Disambiguation: 4,
  Conjugation: 5,
  Source: 6,
  FormalityLevel: 7,
  HonorificRules: 8,
  SemanticVector: 9,
  0: 'Korean',
  1: 'English',
  2: 'PartofSpeech',
  3: 'SemanticTags',
  4: 'Disambiguation',
  5: 'Conjugation',
  6: 'Source',
  7: 'FormalityLevel',
  8: 'HonorificRules',
  9: 'SemanticVector'
};
Object.freeze(DATA_SCHEMA);

const KR_EN_languageUnits = [
  // Vocabulary from SUOBI01
  ["미국 사람", "American person", "Noun", ["person"], "", "", "SUOBI01", "", ""],
  ["이름", "name", "Noun", ["attribute", "koreanRoot"], "", "", "SUOBI01", "", "Replace with 성함 for respected subjects", '{"domain":"attribute", "traits":["identity"]}'],
  ["저", "I", "Pronoun", ["person"], "humble I", "", "SUOBI01", "Formal/Polite", "", '{"domain":"person", "traits":["first_person", "humble"]}'],
  ["제", "my", "Pronoun", ["person"], "humble my", "", "SUOBI01", "Formal/Polite", "", '{"domain":"person", "traits":["first_person", "possessive", "humble"]}'],
  ["네", "yes", "Exclamation", ["greeting"], "", "", "SUOBI01", "Polite", "", '{"logic":"affirmative"}'],
  ["안녕하다", "doing well", "Descriptive Verb", ["descriptive_person", "greeting", "emotion"], "", "regular", "SUOBI01", "", "", '{"domain":"state", "req":"person", "polarity":1}'],
  ["나라", "country", "Noun", ["place"], "", "", "SUOBI01", "", "", '{"domain":"place", "traits":["country"]}'],
  ["노르웨이", "Norway", "Noun", ["place"], "", "", "SUOBI01", "", "", '{"domain":"place", "traits":["country"]}'],
  ["미국", "the U.S.", "Noun", ["place", "devtest"], "", "", "SUOBI01", "", "", '{"domain":"place"}'],
  ["베트남", "Vietnam", "Noun", ["place"], "", "", "SUOBI01", "", "", '{"domain":"place", "traits":["country"]}'],
  ["브라질", "Brazil", "Noun", ["place"], "", "", "SUOBI01", "", "", '{"domain":"place", "traits":["country"]}'],
  ["사람", "person", "Noun", ["person", "koreanRoot", "devtest"], "", "", "SUOBI01", "", "Replace with 분 for respected subjects", '{"domain":"person"}'],
  ["일본", "Japan", "Noun", ["place"], "", "", "SUOBI01", "", "", '{"domain":"place", "traits":["country"]}'],
  ["중국", "China", "Noun", ["place"], "", "", "SUOBI01", "", "", '{"domain":"place", "traits":["country"]}'],
  ["케냐", "Kenya", "Noun", ["place"], "", "", "SUOBI01", "", "", '{"domain":"place", "traits":["country"]}'],
  ["프랑스", "France", "Noun", ["place"], "", "", "SUOBI01", "", "", '{"domain":"place", "traits":["country"]}'],
  ["한국", "Korea", "Noun", ["place"], "", "", "SUOBI01", "", "", '{"domain":"place", "traits":["country"]}'],
  ["한국 사람", "Korean person", "Noun", ["person"], "", "", "SUOBI01", "", "", '{"domain":"person", "traits":["nationality"]}'],
  ["호주", "Australia", "Noun", ["place"], "", "", "SUOBI01", "", "", '{"domain":"place", "traits":["country"]}'],
  ["어느", "which", "Pronoun", ["questionWord"], "", "", "SUOBI01", "", "", '{"logic":"question", "domain":"any"}'],
  ["감사하다", "to be thankful", "Descriptive Verb", ["greeting", "emotion"], "", "hada", "SUOBI01", "Formal", "", '{"domain":"state", "req":"person", "polarity":1}'],
  ["괜찮다", "to be okay", "Descriptive Verb", ["emotion"], "", "regular", "SUOBI01", "", "", '{"domain":"state", "req":"any", "polarity":1}'],
  ["죄송하다", "to be sorry", "Descriptive Verb", ["emotion"], "", "hada", "SUOBI01", "Formal", "", '{"domain":"state", "req":"person", "polarity":-1}'],
  ["씨", "Mr./Ms.", "Noun", ["person", "honorific"], "", "", "SUOBI01", "", "Attached to names", '{"logic":"honorific"}'],
  ["학생", "student", "Noun", ["person", "profession", "sinoRoot"], "", "", "SUOBI01", "", "", '{"domain":"person", "traits":["profession"]}'],
  ["회사원", "company worker", "Noun", ["person", "profession", "sinoRoot"], "", "", "SUOBI01", "", "", '{"domain":"person", "traits":["profession"]}'],
  ["아니요", "no", "Exclamation", ["greeting"], "", "", "SUOBI01", "Polite", "", '{"logic":"negative"}'],
  ["가수", "singer", "Noun", ["person", "profession", "sinoRoot"], "", "", "SUOBI01", "", "", '{"domain":"person", "traits":["profession"]}'],
  ["간호사", "nurse", "Noun", ["person", "profession", "sinoRoot"], "", "", "SUOBI01", "", "", '{"domain":"person", "traits":["profession"]}'],
  ["기자", "journalist", "Noun", ["person", "profession", "sinoRoot"], "", "", "SUOBI01", "", "", '{"domain":"person", "traits":["profession"]}'],
  ["누구", "who", "Pronoun", ["questionWord", "person"], "", "", "SUOBI01", "", "", '{"domain":"person", "traits":["question"]}'],
  ["배우", "actor", "Noun", ["person", "profession", "sinoRoot"], "", "", "SUOBI01", "", "", '{"domain":"person", "traits":["profession"]}'],
  ["선생님", "teacher", "Noun", ["person", "profession", "honorific"], "", "", "SUOBI01", "", "Honorific form included", '{"domain":"person", "traits":["profession", "honorific"]}'],
  ["요리사", "chef", "Noun", ["person", "profession", "sinoRoot"], "", "", "SUOBI01", "", "", '{"domain":"person", "traits":["profession"]}'],
  ["은행원", "bank teller", "Noun", ["person", "profession", "sinoRoot"], "", "", "SUOBI01", "", "", '{"domain":"person", "traits":["profession"]}'],
  ["의사", "doctor", "Noun", ["person", "profession", "sinoRoot", "devtest"], "", "", "SUOBI01", "", "", '{"domain":"person"}'],

  // Grammar from SUOBI01
  ["은 / 는", "topic marker", "Grammar", ["particle", "topic", "devtest"], "Marks the theme or contrast", ["{N}은/는"], "SUOBI01", "", "", '{"logic":"topic"}'],
  ["이에요 / 예요", "polite informal 'to be'", "Grammar", ["declarative", "present", "devtest"], "Attached directly to nouns", ["{N}이/예요"], "SUOBI01", "Polite Informal (해요체)", "", '{"logic":"identify"}'],

  // Extra Vocabulary from SUOBI00 to make interesting sentences
  ["밥", "rice/meal", "Noun", ["food", "koreanRoot", "devtest"], "", "", "SUOBI00", "", "", '{"domain":"food"}'],
  ["물", "water", "Noun", ["drink", "koreanRoot", "devtest"], "", "", "SUOBI00", "", "", '{"domain":"drink"}'],
  ["먹다", "to eat", "Action Verb", ["transitive_food", "koreanRoot", "devtest"], "", "regular_eo", "SUOBI00", "", "Replace with 드시다 for respected subjects", '{"domain":"consume", "req":"food", "prod":"satiety", "polarity": 1}'],
  ["마시다", "to drink", "Action Verb", ["transitive_drink", "koreanRoot", "devtest"], "", "i_irregular", "SUOBI00", "", "Replace with 드시다 for respected subjects", '{"domain":"consume", "req":"drink", "prod":"satiety", "polarity": 1}'],
  ["크다", "to be big", "Descriptive Verb", ["descriptive_general", "koreanRoot", "devtest"], "", "eu_irregular", "SUOBI00", "", "", '{"domain":"state","req":"any","polarity":1}'],
  ["맛있다", "to be delicious", "Descriptive Verb", ["descriptive_food", "food_adjective"], "", "regular", "SUOBI00", "", "", '{"domain":"state", "req":"food", "polarity": 1}'],
  ["가다", "to go", "Action Verb", ["intransitive_motion", "koreanRoot", "devtest"], "", "regular_a", "SUOBI00", "", "", '{"domain":"motion","req":"place"}'],
  ["오늘", "today", "Noun", ["time", "koreanRoot"], "", "", "SUOBI00", "", "", '{"domain":"time", "traits":["present"]}'],
  ["내일", "tomorrow", "Noun", ["time", "sinoRoot"], "", "", "SUOBI00", "", "", '{"domain":"time", "traits":["future"]}'],
  ["자주", "often", "Adverb", ["frequency", "koreanRoot"], "", "", "SUOBI00", "", "", '{"logic":"frequency", "traits":["high"]}'],
  ["가끔", "sometimes", "Adverb", ["frequency", "koreanRoot"], "", "", "SUOBI00", "", "", '{"logic":"frequency", "traits":["low"]}'],


  // Grammar from SUOBI00
  ["~아요 / ~어요 / ~해요", "polite ending", "Grammar", ["declarative", "interrogative", "present", "devtest"], "", ["{AVst}아/어요", "{DVst}아/어요"], "SUOBI00", "Polite Informal (해요체)", "", '{"logic":"declarative"}'],
  ["~습니다 / ~ㅂ니다", "formal polite declarative ending", "Grammar", ["declarative", "present", "honorific", "devtest"], "", ["{AVst}습니다/ㅂ니다", "{DVst}습니다/ㅂ니다"], "SUOBI00", "Formal Polite (합쇼체)", "", '{"logic":"declarative"}'],
  ["~자", "let's do...", "Grammar", ["suggestion"], "", ["{AVst}자"], "SUOBI00", "Plain (한다체)", "Cannot be used with honorific subject"],
  ["-아/어서", "because / so", "Grammar", ["reason", "conjunction", "sequential"], "", ["{VP_AVst}아/어서 {Clause}", "{VP_DVst}아/어서 {Clause}"], "SUOBI00", "", "No past tense in first clause"],
  ["-(으)니까", "since / because", "Grammar", ["reason", "conjunction", "devtest"], "", ["{VP_AVst}으/니까 {Clause}", "{VP_DVst}으/니까 {Clause}"], "SUOBI00", "", "Often followed by imperative or propositive", JSON.stringify({logic:"cause_effect", polarity_match: true})],
  ["-기 때문에", "because of", "Grammar", ["reason", "conjunction"], "", ["{VP_AVst}기 때문에 {Clause}", "{VP_DVst}기 때문에 {Clause}", "{N} 때문에 {Clause}"], "SUOBI00", "", ""],
  ["이다", "to be", "Descriptive Verb", ["particle"], "", "regular", "SUOBI00", "", "Copula verb", '{"logic":"identify"}'],
  ["입니다", "is/are", "Grammar", ["declarative", "present", "honorific"], "", ["{N}입니다"], "SUOBI00", "Formal Polite (합쇼체)", ""],

  // Vocabulary from SUOBI02
  ["교실", "classroom", "Noun", ["place", "sinoRoot"], "", "", "SUOBI02", "", "", '{"domain":"place", "traits":["room"]}'],
  ["그것", "that (near you)", "Pronoun", ["demonstrative"], "", "", "SUOBI02", "", "", '{"domain":"object", "traits":["demonstrative"]}'],
  ["무엇", "what", "Pronoun", ["questionWord", "thing"], "", "", "SUOBI02", "", "", '{"domain":"object", "traits":["question"]}'],
  ["여기", "here", "Pronoun", ["place"], "", "", "SUOBI02", "", "", '{"domain":"place", "traits":["demonstrative"]}'],
  ["우리", "we/us/our", "Pronoun", ["person"], "", "", "SUOBI02", "", "", '{"domain":"person", "traits":["first_person", "plural"]}'],
  ["이것", "this (thing)", "Pronoun", ["demonstrative"], "", "", "SUOBI02", "", "", '{"domain":"object", "traits":["demonstrative"]}'],
  ["컴퓨터", "computer", "Noun", ["object", "devtest"], "", "", "SUOBI02", "", "", '{"domain":"object"}'],
  ["거울", "mirror", "Noun", ["object"], "", "", "SUOBI02", "", "", '{"domain":"object"}'],
  ["누가", "who (subject)", "Pronoun", ["questionWord", "person", "devtest"], "subject is unknown person", "", "SUOBI02", "", "", '{"domain":"person"}'],
  ["달력", "calendar", "Noun", ["object"], "", "", "SUOBI02", "", "", '{"domain":"object"}'],
  ["지도", "map", "Noun", ["object"], "", "", "SUOBI02", "", "", '{"domain":"object"}'],
  ["문", "door", "Noun", ["object", "sinoRoot"], "", "", "SUOBI02", "", "", '{"domain":"object"}'],
  ["시계", "clock", "Noun", ["object", "sinoRoot"], "", "", "SUOBI02", "", "", '{"domain":"object"}'],
  ["옷걸이", "coat hanger", "Noun", ["object"], "", "", "SUOBI02", "", "", '{"domain":"object"}'],
  ["의자", "chair", "Noun", ["object"], "", "", "SUOBI02", "", "", '{"domain":"object"}'],
  ["저것", "that (thing)", "Pronoun", ["demonstrative"], "", "", "SUOBI02", "", "", '{"domain":"object", "traits":["demonstrative"]}'],
  ["창문", "window", "Noun", ["object", "sinoRoot"], "", "", "SUOBI02", "", "", '{"domain":"object"}'],
  ["책상", "desk", "Noun", ["object", "sinoRoot"], "", "", "SUOBI02", "", "", '{"domain":"object"}'],
  ["친구", "friend", "Noun", ["person", "sinoRoot"], "", "", "SUOBI02", "", "", '{"domain":"person", "traits":["relationship"]}'],
  ["칠판", "blackboard", "Noun", ["object", "sinoRoot"], "", "", "SUOBI02", "", "", '{"domain":"object"}'],
  ["텔레비전", "television", "Noun", ["object"], "", "", "SUOBI02", "", "", '{"domain":"object"}'],
  ["공책", "notebook", "Noun", ["object", "sinoRoot"], "", "", "SUOBI02", "", "", '{"domain":"object"}'],
  ["책", "book", "Noun", ["object", "sinoRoot"], "", "", "SUOBI02", "", "", '{"domain":"object"}'],
  ["없다", "to not have", "Descriptive Verb", ["descriptive_general", "existence"], "", "regular", "SUOBI02", "", "Replace with 계시다 for respected subjects", '{"domain":"state", "req":"object", "polarity":-1}'],
  ["있다", "to have", "Descriptive Verb", ["descriptive_general", "existence"], "", "regular", "SUOBI02", "", "Replace with 계시다 for respected subjects", '{"domain":"state", "req":"object", "polarity":1}'],
  ["가방", "bag", "Noun", ["object"], "", "", "SUOBI02", "", "", '{"domain":"object"}'],
  ["돈", "money", "Noun", ["object"], "", "", "SUOBI02", "", "", '{"domain":"object"}'],
  ["볼펜", "pen", "Noun", ["object"], "", "", "SUOBI02", "", "", '{"domain":"object"}'],
  ["신문", "newspaper", "Noun", ["object", "sinoRoot"], "", "", "SUOBI02", "", "", '{"domain":"object"}'],
  ["연필", "pencil", "Noun", ["object"], "", "", "SUOBI02", "", "", '{"domain":"object"}'],
  ["잡지", "magazine", "Noun", ["object", "sinoRoot"], "", "", "SUOBI02", "", "", '{"domain":"object"}'],
  ["지갑", "wallet", "Noun", ["object"], "", "", "SUOBI02", "", "", '{"domain":"object"}'],
  ["지우개", "eraser", "Noun", ["object"], "", "", "SUOBI02", "", "", '{"domain":"object"}'],
  ["필통", "pencil case", "Noun", ["object"], "", "", "SUOBI02", "", "", '{"domain":"object"}'],
  ["학생증", "student ID card", "Noun", ["object", "sinoRoot"], "", "", "SUOBI02", "", "", '{"domain":"object"}'],
  ["휴대전화", "cell phone", "Noun", ["object", "sinoRoot"], "", "", "SUOBI02", "", "", '{"domain":"object"}'],
  ["휴지", "tissue", "Noun", ["object"], "", "", "SUOBI02", "", "", '{"domain":"object"}'],

  // Grammar from SUOBI02
  ["이/가 아니에요", "to not be", "Grammar", ["declarative", "negative"], "", ["{N}이/가 아니에요"], "SUOBI02", "Polite Informal (해요체)", "Replace with 께서 for respected subjects"],
  ["이 / 가", "subject marker", "Grammar", ["particle", "subject"], "Marks the grammatical subject", ["{N}이/가"], "SUOBI02", "", "Replace with 께서 for respected subjects"],

  // Vocabulary from SUOBI03
  ["도서관", "library", "Noun", ["place", "sinoRoot"], "", "", "SUOBI03", "", ""],
  ["안", "inside", "Noun", ["position"], "", "", "SUOBI03", "", ""],
  ["앞", "front", "Noun", ["position"], "", "", "SUOBI03", "", ""],
  ["어디", "where", "Pronoun", ["questionWord", "place"], "", "", "SUOBI03", "", ""],
  ["은행", "bank", "Noun", ["place", "sinoRoot"], "", "", "SUOBI03", "", ""],
  ["학생회관", "student union", "Noun", ["place", "sinoRoot"], "", "", "SUOBI03", "", ""],
  ["기숙사", "dormitory", "Noun", ["place", "sinoRoot"], "", "", "SUOBI03", "", ""],
  ["꽃", "flower", "Noun", ["object"], "", "", "SUOBI03", "", ""],
  ["뒤", "behind", "Noun", ["position"], "", "", "SUOBI03", "", ""],
  ["밖", "outside", "Noun", ["position"], "", "", "SUOBI03", "", ""],
  ["사무실", "office", "Noun", ["place", "sinoRoot"], "", "", "SUOBI03", "", ""],
  ["서점", "bookstore", "Noun", ["place", "sinoRoot"], "", "", "SUOBI03", "", ""],
  ["식당", "restaurant", "Noun", ["place", "sinoRoot"], "", "", "SUOBI03", "", ""],
  ["아래", "below/under", "Noun", ["position"], "", "", "SUOBI03", "", ""],
  ["옆", "next to", "Noun", ["position"], "", "", "SUOBI03", "", ""],
  ["우체국", "post office", "Noun", ["place", "sinoRoot"], "", "", "SUOBI03", "", ""],
  ["위", "above", "Noun", ["position"], "", "", "SUOBI03", "", ""],
  ["저기", "over there", "Pronoun", ["place"], "", "", "SUOBI03", "", ""],
  ["체육관", "gym", "Noun", ["place", "sinoRoot"], "", "", "SUOBI03", "", ""],
  ["편의점", "convenience store", "Noun", ["place", "sinoRoot"], "", "", "SUOBI03", "", ""],
  ["근처", "near", "Noun", ["position"], "", "", "SUOBI03", "", ""],
  ["방", "room", "Noun", ["place"], "", "", "SUOBI03", "", ""],
  ["학생식당", "student cafeteria", "Noun", ["place", "sinoRoot"], "", "", "SUOBI03", "", ""],
  ["어떻다", "to be how", "Descriptive Verb", ["descriptive_general", "questionWord", "devtest"], "", "h_irregular", "SUOBI03", "", "", '{"domain":"state"}'],
  ["좋다", "to be good", "Descriptive Verb", ["descriptive_general", "emotion"], "", "regular", "SUOBI03", "", "", JSON.stringify({domain:"state", req:"any", polarity: 1})],
  ["아주", "very", "Adverb", ["degree"], "", "", "SUOBI03", "", ""],
  ["날씨", "weather", "Noun", ["attribute"], "", "", "SUOBI03", "", ""],
  ["나쁘다", "to be bad", "Descriptive Verb", ["descriptive_general"], "", "eu_irregular", "SUOBI03", "", ""],
  ["덥다", "to be hot", "Descriptive Verb", ["descriptive_general", "devtest"], "", "b_irregular", "SUOBI03", "", "", '{"domain":"state","req":"any","polarity":-1}'],
  ["많다", "to be many/much", "Descriptive Verb", ["descriptive_general", "quantity"], "", "regular", "SUOBI03", "", ""],
  ["시끄럽다", "to be noisy", "Descriptive Verb", ["descriptive_general"], "", "b_irregular", "SUOBI03", "", ""],
  ["작다", "to be small", "Descriptive Verb", ["descriptive_general"], "", "regular", "SUOBI03", "", ""],
  ["적다", "to be little/few", "Descriptive Verb", ["descriptive_general", "quantity"], "", "regular", "SUOBI03", "", ""],
  ["조용하다", "to be quiet", "Descriptive Verb", ["descriptive_general"], "", "hada", "SUOBI03", "", ""],
  ["춥다", "to be cold", "Descriptive Verb", ["descriptive_general"], "", "b_irregular", "SUOBI03", "", ""],

  // Grammar from SUOBI03
  ["에 (location)", "location marker", "Grammar", ["particle", "location", "devtest"], "Expresses location of (with 있다/없다)", ["{N}에 있다/없다"], "SUOBI03", "", "", '{"logic":"location"}'],
  ,

  // Vocabulary from SUOBI04
  ["저분", "that person (honorific)", "Noun", ["person", "honorific"], "", "", "SUOBI04", "", ""],
  ["한국말", "Korean language", "Noun", ["language", "object"], "", "", "SUOBI04", "", ""],
  ["배우다", "to learn", "Action Verb", ["transitive_general"], "", "regular", "SUOBI04", "", ""],
  ["오다", "to come", "Action Verb", ["intransitive_motion"], "", "regular", "SUOBI04", "", ""],
  ["베트남말", "Vietnamese language", "Noun", ["language", "object"], "", "", "SUOBI04", "", ""],
  ["빵", "bread", "Noun", ["food"], "", "", "SUOBI04", "", "", JSON.stringify({domain:"food"})],
  ["영어", "English language", "Noun", ["language", "object", "sinoRoot"], "", "", "SUOBI04", "", ""],
  ["음악", "Music", "Noun", ["object", "sinoRoot"], "", "", "SUOBI04", "", ""],
  ["일본말", "Japanese language", "Noun", ["language", "object"], "", "", "SUOBI04", "", ""],
  ["중국말", "Chinese language", "Noun", ["language", "object"], "", "", "SUOBI04", "", ""],
  ["커피", "coffee", "Noun", ["drink"], "", "", "SUOBI04", "", "", JSON.stringify({domain:"drink"})],
  ["프랑스말", "French language", "Noun", ["language", "object"], "", "", "SUOBI04", "", ""],
  ["가르치다", "to teach", "Action Verb", ["transitive_general"], "", "regular", "SUOBI04", "", ""],
  ["기다리다", "to wait", "Action Verb", ["transitive_general"], "", "regular", "SUOBI04", "", ""],
  ["듣다", "to listen/hear", "Action Verb", ["transitive_general"], "", "d_irregular", "SUOBI04", "", ""],
  ["만나다", "to meet", "Action Verb", ["transitive_person"], "", "regular", "SUOBI04", "", ""],
  ["보다", "to see/watch", "Action Verb", ["transitive_general"], "", "regular", "SUOBI04", "", ""],
  ["사다", "to buy", "Action Verb", ["transitive_general"], "", "regular", "SUOBI04", "", ""],
  ["쓰다", "to write", "Action Verb", ["transitive_general"], "", "eu_irregular", "SUOBI04", "", ""],
  ["읽다", "to read", "Action Verb", ["transitive_general"], "", "regular", "SUOBI04", "", ""],
  ["입다", "to wear", "Action Verb", ["transitive_general"], "", "regular", "SUOBI04", "", ""],
  ["지금", "now", "Noun", ["time"], "", "", "SUOBI04", "", ""],
  ["게임", "game", "Noun", ["object"], "", "", "SUOBI04", "", ""],
  ["날마다", "everyday", "Adverb", ["frequency"], "", "", "SUOBI04", "", ""],
  ["피시방", "internet cafe", "Noun", ["place"], "", "", "SUOBI04", "", ""],
  ["하다", "to do", "Action Verb", ["transitive_general"], "", "hada", "SUOBI04", "", ""],
  ["꽃집", "flower shop", "Noun", ["place"], "", "", "SUOBI04", "", ""],
  ["노래방", "karaoke", "Noun", ["place"], "", "", "SUOBI04", "", ""],
  ["문구점", "stationery store", "Noun", ["place"], "", "", "SUOBI04", "", ""],
  ["백화점", "department store", "Noun", ["place"], "", "", "SUOBI04", "", ""],
  ["빵집", "bakery", "Noun", ["place"], "", "", "SUOBI04", "", ""],
  ["찜질방", "korean sauna", "Noun", ["place"], "", "", "SUOBI04", "", ""],
  ["태권도", "taekwondo", "Noun", ["object"], "", "", "SUOBI04", "", ""],
  ["게임하다", "to play games", "Action Verb", ["intransitive_general"], "", "hada", "SUOBI04", "", ""],
  ["공부하다", "to study", "Action Verb", ["transitive_general"], "", "hada", "SUOBI04", "", ""],
  ["노래하다", "to sing", "Action Verb", ["intransitive_general"], "", "hada", "SUOBI04", "", ""],
  ["식사하다", "to have a meal", "Action Verb", ["intransitive_general"], "", "hada", "SUOBI04", "", ""],
  ["아르바이트하다", "to work part time", "Action Verb", ["intransitive_general"], "", "hada", "SUOBI04", "", ""],
  ["운동하다", "to exercise", "Action Verb", ["intransitive_general"], "", "hada", "SUOBI04", "", ""],
  ["일하다", "to work", "Action Verb", ["intransitive_general"], "", "hada", "SUOBI04", "", ""],

  // Grammar from SUOBI04
  ["을 / 를", "object marker", "Grammar", ["particle", "object"], "", ["{N}을/를"], "SUOBI04", "", ""],

  // Vocabulary from SUOBI05
  ["고향", "hometown", "Noun", ["place"], "", "", "SUOBI05", "", ""],
  ["바다", "ocean", "Noun", ["place"], "", "", "SUOBI05", "", ""],
  ["수영", "swimming", "Noun", ["activity"], "", "", "SUOBI05", "", ""],
  ["언제", "when", "Pronoun", ["questionWord", "time"], "", "", "SUOBI05", "", ""],
  ["강", "river", "Noun", ["place"], "", "", "SUOBI05", "", ""],
  ["산", "mountain", "Noun", ["place"], "", "", "SUOBI05", "", ""],
  ["집", "house/home", "Noun", ["place"], "", "", "SUOBI05", "", "Replace with 댁 for respected subjects"],
  ["호수", "lake", "Noun", ["place"], "", "", "SUOBI05", "", ""],
  ["회사", "company", "Noun", ["place"], "", "", "SUOBI05", "", ""],
  ["서울", "Seoul", "Noun", ["place"], "", "", "SUOBI05", "", ""],
  ["복잡하다", "to be crowded/complicated", "Descriptive Verb", ["descriptive_place"], "", "hada", "SUOBI05", "", ""],
  ["아름답다", "to be beautiful", "Descriptive Verb", ["descriptive_place", "descriptive_person"], "", "b_irregular", "SUOBI05", "", ""],
  ["경치", "scenery", "Noun", ["attribute"], "", "", "SUOBI05", "", ""],
  ["남자", "man", "Noun", ["person"], "", "", "SUOBI05", "", ""],
  ["생선", "fish (food)", "Noun", ["food"], "", "", "SUOBI05", "", ""],
  ["생활", "life/living", "Noun", ["attribute"], "", "", "SUOBI05", "", ""],
  ["여자", "woman", "Noun", ["person"], "", "", "SUOBI05", "", ""],
  ["깨끗하다", "to be clean", "Descriptive Verb", ["descriptive_place", "descriptive_general"], "", "hada", "SUOBI05", "", ""],
  ["더럽다", "to be dirty", "Descriptive Verb", ["descriptive_place", "descriptive_general", "devtest"], "", "b_irregular", "SUOBI05", "", "", '{"domain":"state","req":"any","polarity":-1}'],
  ["바쁘다", "to be busy", "Descriptive Verb", ["descriptive_person", "devtest"], "", "eu_irregular", "SUOBI05", "", "", '{"domain":"state","req":"person","polarity":-1}'],
  ["예쁘다", "to be pretty", "Descriptive Verb", ["descriptive_person", "devtest"], "", "eu_irregular", "SUOBI05", "", "", '{"domain":"state","req":"person","polarity":1}'],
  ["재미없다", "to be not fun", "Descriptive Verb", ["descriptive_general"], "", "regular", "SUOBI05", "", ""],
  ["재미있다", "to be fun", "Descriptive Verb", ["descriptive_general"], "", "regular", "SUOBI05", "", ""],
  ["친절하다", "to be kind", "Descriptive Verb", ["descriptive_person"], "", "hada", "SUOBI05", "", ""],
  ["한가하다", "to be not busy", "Descriptive Verb", ["descriptive_person"], "", "hada", "SUOBI05", "", ""],

  // Grammar from SUOBI05
  ["에서", "location action marker", "Grammar", ["particle", "location_action"], "", ["{N}에서 {VP_AVst}"], "SUOBI05", "", ""],
  ["에 (direction)", "direction marker", "Grammar", ["particle", "direction"], "", ["{N}에 {VP_AVst}"], "SUOBI05", "", ""], // Wait, intransitive_motion verbs already use 에 in generator, we don't necessarily need a grammar rule, but we can have it

  // Vocabulary from SUOBI06
  ["몇", "what/how many", "Pronoun", ["questionWord", "number"], "", "", "SUOBI06", "", ""],
  ["반", "half", "Noun", ["time_amount"], "", "", "SUOBI06", "", ""],
  ["보통", "usually", "Adverb", ["frequency"], "", "", "SUOBI06", "", ""],
  ["시", "hour/o'clock", "Noun", ["measureWord", "koreanMeasureWord"], "", "", "SUOBI06", "", ""],
  ["아홉", "nine", "Number", ["koreanNumber"], "", "", "SUOBI06", "", ""],
  ["점심", "lunch", "Noun", ["time", "meal"], "", "", "SUOBI06", "", ""],
  ["한", "one", "Number", ["koreanNumber"], "", "", "SUOBI06", "", ""],
  ["아침", "morning/breakfast", "Noun", ["time", "meal"], "", "", "SUOBI06", "", ""],
  ["영화", "movie", "Noun", ["object"], "", "", "SUOBI06", "", ""],
  ["오전", "morning/AM", "Noun", ["time"], "", "", "SUOBI06", "", ""],
  ["오후", "afternoon/PM", "Noun", ["time"], "", "", "SUOBI06", "", ""],
  ["저녁", "dinner/evening", "Noun", ["time", "meal"], "", "", "SUOBI06", "", ""],
  ["두", "two", "Number", ["koreanNumber"], "", "", "SUOBI06", "", ""],
  ["세", "three", "Number", ["koreanNumber"], "", "", "SUOBI06", "", ""],
  ["네", "four", "Number", ["koreanNumber"], "", "", "SUOBI06", "", "", '{"logic":"affirmative"}'],
  ["다섯", "five", "Number", ["koreanNumber"], "", "", "SUOBI06", "", ""],
  ["여섯", "six", "Number", ["koreanNumber"], "", "", "SUOBI06", "", ""],
  ["일곱", "seven", "Number", ["koreanNumber"], "", "", "SUOBI06", "", ""],
  ["여덟", "eight", "Number", ["koreanNumber"], "", "", "SUOBI06", "", ""],
  ["열", "ten", "Number", ["koreanNumber"], "", "", "SUOBI06", "", ""],
  ["열한", "eleven", "Number", ["koreanNumber"], "", "", "SUOBI06", "", ""],
  ["열두", "twelve", "Number", ["koreanNumber"], "", "", "SUOBI06", "", ""],
  ["삼십", "thirty", "Number", ["sinoNumber"], "", "", "SUOBI06", "", ""],
  ["교과서", "textbook", "Noun", ["object"], "", "", "SUOBI06", "", ""],
  ["대화", "conversation", "Noun", ["activity"], "", "", "SUOBI06", "", ""],
  ["번", "times/number", "Noun", ["measureWord", "koreanMeasureWord"], "", "", "SUOBI06", "", ""],
  ["수업", "class", "Noun", ["activity"], "", "", "SUOBI06", "", ""],
  ["숙제", "homework", "Noun", ["activity"], "", "", "SUOBI06", "", ""],
  ["쪽", "page", "Noun", ["measureWord", "sinoMeasureWord"], "", "", "SUOBI06", "", ""],
  ["알다", "to know/understand", "Action Verb", ["transitive_general"], "", "l_irregular", "SUOBI06", "", ""],
  ["고맙다", "to be thankful", "Descriptive Verb", ["emotion"], "", "b_irregular", "SUOBI06", "", ""],
  ["닫다", "to close", "Action Verb", ["transitive_general"], "", "regular", "SUOBI06", "", ""],
  ["운전하다", "to drive", "Action Verb", ["transitive_general", "intransitive_general"], "", "hada", "SUOBI06", "", ""],
  ["전화하다", "to call", "Action Verb", ["transitive_person"], "", "hada", "SUOBI06", "", ""],
  ["피곤하다", "to be tired", "Descriptive Verb", ["descriptive_person"], "", "hada", "SUOBI06", "", ""],
  ["일", "one", "Number", ["sinoNumber"], "", "", "SUOBI06", "", ""],
  ["이", "two", "Number", ["sinoNumber"], "", "", "SUOBI06", "", ""],
  ["삼", "three", "Number", ["sinoNumber"], "", "", "SUOBI06", "", ""],
  ["사", "four", "Number", ["sinoNumber"], "", "", "SUOBI06", "", ""],
  ["오", "five", "Number", ["sinoNumber"], "", "", "SUOBI06", "", ""],
  ["육", "six", "Number", ["sinoNumber"], "", "", "SUOBI06", "", ""],
  ["칠", "seven", "Number", ["sinoNumber"], "", "", "SUOBI06", "", ""],
  ["팔", "eight", "Number", ["sinoNumber"], "", "", "SUOBI06", "", ""],
  ["구", "nine", "Number", ["sinoNumber"], "", "", "SUOBI06", "", ""],
  ["십", "ten", "Number", ["sinoNumber"], "", "", "SUOBI06", "", ""],
  ["이십", "twenty", "Number", ["sinoNumber"], "", "", "SUOBI06", "", ""],
  ["사십", "forty", "Number", ["sinoNumber"], "", "", "SUOBI06", "", ""],
  ["오십", "fifty", "Number", ["sinoNumber"], "", "", "SUOBI06", "", ""],
  ["분", "minute", "Noun", ["measureWord", "sinoMeasureWord"], "", "", "SUOBI06", "", ""],
  ["나이", "age", "Noun", ["attribute"], "", "", "SUOBI06", "", "Honorific: 연세"],
  ["안", "not", "Adverb", ["negative"], "", "", "SUOBI06", "", ""],

  // Grammar from SUOBI06
  ["-지 않다", "to not do/be", "Grammar", ["negative"], "", ["{VP_AVst}지 않아요", "{VP_DVst}지 않아요"], "SUOBI06", "", ""],
  ["에 (time)", "time marker", "Grammar", ["particle", "time"], "", ["{N:time}에 {VP_AVst}"], "SUOBI06", "", ""],
  ["(이)랑", "and/with", "Grammar", ["particle", "conjunction"], "", ["{N}(이)랑 {N}이/가 {VP_DVst}"], "SUOBI06", "", ""],
  ["시간 표현", "time expression", "Grammar", ["N_Phrase", "time"], "", ["{Number:koreanNumber} 시 {Number:sinoNumber} 분"], "SUOBI06", "", ""],
  ["횟수 표현", "number of times", "Grammar", ["Adv"], "", ["{Number:koreanNumber} 번"], "SUOBI06", "", ""]
  ,

  // Vocabulary from SUOBI07
  ["불고기", "bulgogi", "Noun", ["food"], "", "", "SUOBI07", "", ""],
  ["만들다", "to make", "Action Verb", ["transitive_general"], "", "l_irregular", "SUOBI07", "", ""],
  ["맵다", "to be spicy", "Descriptive Verb", ["descriptive_food"], "", "b_irregular", "SUOBI07", "", ""],
  ["좋아하다", "to like", "Action Verb", ["transitive_general", "transitive_food"], "", "hada", "SUOBI07", "", ""],
  ["무슨", "what kind", "Noun", ["questionWord", "modifier"], "", "", "SUOBI07", "", ""],
  ["그럼", "then", "Adverb", ["conjunction"], "", "", "SUOBI07", "", ""],
  ["과일", "fruit", "Noun", ["food"], "", "", "SUOBI07", "", ""],
  ["냉면", "cold noodles", "Noun", ["food"], "", "", "SUOBI07", "", ""],
  ["녹차", "green tea", "Noun", ["drink"], "", "", "SUOBI07", "", ""],
  ["딸기", "strawberry", "Noun", ["food"], "", "", "SUOBI07", "", ""],
  ["맛", "taste", "Noun", ["attribute"], "", "", "SUOBI07", "", ""],
  ["비빔밥", "bibimbap", "Noun", ["food"], "", "", "SUOBI07", "", ""],
  ["사과", "apple", "Noun", ["food"], "", "", "SUOBI07", "", ""],
  ["삼계탕", "ginseng chicken soup", "Noun", ["food"], "", "", "SUOBI07", "", ""],
  ["샌드위치", "sandwich", "Noun", ["food"], "", "", "SUOBI07", "", ""],
  ["서양", "western", "Noun", ["place"], "", "", "SUOBI07", "", ""],
  ["액션영화", "action movie", "Noun", ["object"], "", "", "SUOBI07", "", ""],
  ["우동", "udon", "Noun", ["food"], "", "", "SUOBI07", "", ""],
  ["유자차", "citron tea", "Noun", ["drink"], "", "", "SUOBI07", "", ""],
  ["음식", "food", "Noun", ["food"], "", "", "SUOBI07", "", ""],
  ["자장면", "jajangmyeon", "Noun", ["food"], "", "", "SUOBI07", "", ""],
  ["짬뽕", "jjamppong", "Noun", ["food"], "", "", "SUOBI07", "", ""],
  ["차", "tea", "Noun", ["drink"], "", "", "SUOBI07", "", ""],
  ["초밥", "sushi", "Noun", ["food"], "", "", "SUOBI07", "", ""],
  ["코미디 영화", "comedy movie", "Noun", ["object"], "", "", "SUOBI07", "", ""],
  ["피자", "pizza", "Noun", ["food"], "", "", "SUOBI07", "", ""],
  ["맛없다", "to be not delicious", "Descriptive Verb", ["descriptive_food"], "", "regular", "SUOBI07", "", ""],
  ["길다", "to be long", "Descriptive Verb", ["descriptive_general", "devtest"], "", "l_irregular", "SUOBI07", "", "", '{"domain":"state","req":"any","polarity":1}'],
  ["놀다", "to play/hang out", "Action Verb", ["intransitive_general", "devtest"], "", "l_irregular", "SUOBI07", "", "", '{"domain":"action","req":"person"}'],
  ["달다", "to be sweet", "Descriptive Verb", ["descriptive_food", "devtest"], "", "l_irregular", "SUOBI07", "", "", '{"domain":"state","req":"food","polarity":1}'],
  ["멀다", "to be far", "Descriptive Verb", ["descriptive_place", "devtest"], "", "l_irregular", "SUOBI07", "", "", '{"domain":"state","req":"place","polarity":-1}'],
  ["살다", "to live", "Action Verb", ["intransitive_motion", "devtest"], "", "l_irregular", "SUOBI07", "", "", '{"domain":"action","req":"person"}'],
  ["열다", "to open", "Action Verb", ["transitive_general", "devtest"], "", "l_irregular", "SUOBI07", "", "", '{"domain":"action","req":"object"}'],
  ["그릇", "bowl", "Noun", ["measureWord", "sinoMeasureWord", "koreanMeasureWord", "devtest"], "", "", "SUOBI07", "", "", '{"domain":"object"}'],
  ["삼겹살", "pork belly", "Noun", ["food"], "", "", "SUOBI07", "", ""],
  ["인분", "portion", "Noun", ["measureWord", "sinoMeasureWord"], "", "", "SUOBI07", "", ""],
  ["시키다", "to order", "Action Verb", ["transitive_general", "transitive_food", "transitive_drink"], "", "regular", "SUOBI07", "", ""],
  ["주다", "to give", "Action Verb", ["transitive_general"], "", "regular", "SUOBI07", "", ""],
  ["여기요", "excuse me, over here!", "Exclamation", ["greeting"], "", "", "SUOBI07", "", ""],
  ["배가 고프다", "to be hungry", "Descriptive Verb", ["descriptive_person"], "", "eu_irregular", "SUOBI07", "", ""],
  ["같이", "together", "Adverb", ["accompaniment", "devtest"], "", "", "SUOBI07", "", "", '{"logic":"adverb"}'],
  ["김밥", "kimbap", "Noun", ["food"], "", "", "SUOBI07", "", ""],
  ["맥주", "beer", "Noun", ["drink"], "", "", "SUOBI07", "", ""],
  ["앉다", "to sit", "Action Verb", ["intransitive_motion"], "", "regular", "SUOBI07", "", ""],
  ["개", "item", "Noun", ["measureWord", "koreanMeasureWord"], "", "", "SUOBI07", "", ""],
  ["마리", "animal counter", "Noun", ["measureWord", "koreanMeasureWord"], "", "", "SUOBI07", "", ""],
  ["병", "bottle", "Noun", ["measureWord", "koreanMeasureWord"], "", "", "SUOBI07", "", ""],
  ["잔", "cup", "Noun", ["measureWord", "koreanMeasureWord"], "", "", "SUOBI07", "", ""],
  ["줄", "row", "Noun", ["measureWord", "koreanMeasureWord"], "", "", "SUOBI07", "", ""],
  ["판", "plate/pan", "Noun", ["measureWord", "koreanMeasureWord"], "", "", "SUOBI07", "", ""],

  // Grammar from SUOBI07
  ["~았/었어요", "past tense", "Grammar", ["declarative", "past"], "", ["{AVst}았/었어요", "{DVst}았/었어요"], "SUOBI07", "Polite Informal", ""],
  ["~고", "and (clausal)", "Grammar", ["conjunction"], "", ["{VP_AVst}고 {Clause}", "{VP_DVst}고 {Clause}"], "SUOBI07", "", ""]
  ,

  // Vocabulary from SUOBI08
  ["오늘", "today", "Noun", ["time"], "", "", "SUOBI08", "", "", '{"domain":"time", "traits":["present"]}'],
  ["요일", "day of the week", "Noun", ["time"], "", "", "SUOBI08", "", ""],
  ["토요일", "Saturday", "Noun", ["time"], "", "", "SUOBI08", "", ""],
  ["며칠", "what date", "Pronoun", ["questionWord", "time"], "", "", "SUOBI08", "", ""],
  ["생일", "birthday", "Noun", ["time", "event"], "", "", "SUOBI08", "", ""],
  ["크리스마스", "Christmas", "Noun", ["time", "event"], "", "", "SUOBI08", "", ""],
  ["월요일", "Monday", "Noun", ["time"], "", "", "SUOBI08", "", ""],
  ["화요일", "Tuesday", "Noun", ["time"], "", "", "SUOBI08", "", ""],
  ["수요일", "Wednesday", "Noun", ["time"], "", "", "SUOBI08", "", ""],
  ["목요일", "Thursday", "Noun", ["time"], "", "", "SUOBI08", "", ""],
  ["금요일", "Friday", "Noun", ["time"], "", "", "SUOBI08", "", ""],
  ["일요일", "Sunday", "Noun", ["time"], "", "", "SUOBI08", "", ""],
  ["월", "month", "Noun", ["time"], "", "", "SUOBI08", "", ""],
  ["일", "day", "Noun", ["time"], "", "", "SUOBI08", "", ""],
  ["산책", "stroll", "Noun", ["activity"], "", "", "SUOBI08", "", ""],
  ["샤워하다", "to take a shower", "Action Verb", ["intransitive_general"], "", "hada", "SUOBI08", "", ""],
  ["그리고", "and", "Adverb", ["conjunction"], "", "", "SUOBI08", "", ""],
  ["먼저", "first", "Adverb", ["sequence"], "", "", "SUOBI08", "", ""],
  ["뭘", "what", "Pronoun", ["questionWord", "object", "devtest"], "", "", "SUOBI08", "", "", '{"domain":"object"}'],
  ["끝나다", "to finish", "Action Verb", ["intransitive_general"], "", "regular", "SUOBI08", "", ""],
  ["세수하다", "to wash one's face", "Action Verb", ["intransitive_general"], "", "hada", "SUOBI08", "", ""],
  ["일어나다", "to wake up", "Action Verb", ["intransitive_general"], "", "regular", "SUOBI08", "", ""],
  ["자다", "to sleep", "Action Verb", ["intransitive_general"], "", "regular", "SUOBI08", "", "Honorific: 주무시다"],
  ["닦다", "to brush/wipe", "Action Verb", ["transitive_general"], "", "regular", "SUOBI08", "", ""],
  ["이", "teeth", "Noun", ["bodyPart", "devtest"], "", "", "SUOBI08", "", "", '{"domain":"body"}'],
  ["걷다", "to walk", "Action Verb", ["intransitive_motion", "devtest"], "", "d_irregular", "SUOBI08", "", "", '{"domain":"motion","req":"place"}'],
  ["묻다", "to ask", "Action Verb", ["transitive_person", "devtest"], "", "d_irregular", "SUOBI08", "", "", '{"domain":"action","req":"person"}'],
  ["싣다", "to load", "Action Verb", ["transitive_general", "devtest"], "", "d_irregular", "SUOBI08", "", "", '{"domain":"action","req":"object"}'],
  ["받다", "to receive", "Action Verb", ["transitive_general", "devtest"], "", "regular", "SUOBI08", "", "", '{"domain":"action","req":"object"}'],

  // Grammar from SUOBI08
  ["도", "also", "Grammar", ["particle", "also"], "", ["{N}도 {VP_AVst}"], "SUOBI08", "", ""],
  ["하고", "and/with", "Grammar", ["particle", "conjunction"], "", ["{N}하고 {N}이/가 {VP_DVst}"], "SUOBI08", "", ""]
  ,

  // Vocabulary from SUOBI09
  ["운동장", "playground", "Noun", ["place"], "", "", "SUOBI09", "", ""],
  ["주말", "weekend", "Noun", ["time"], "", "", "SUOBI09", "", ""],
  ["축구", "soccer", "Noun", ["activity", "sports"], "", "", "SUOBI09", "", ""],
  ["힘들다", "to be hard", "Descriptive Verb", ["descriptive_general", "descriptive_person"], "", "l_irregular", "SUOBI09", "", ""],
  ["자주", "often", "Adverb", ["frequency"], "", "", "SUOBI09", "", "", '{"logic":"frequency", "traits":["high"]}'],
  ["좀", "little", "Adverb", ["quantity"], "", "", "SUOBI09", "", ""],
  ["골프", "golf", "Noun", ["activity", "sports"], "", "", "SUOBI09", "", ""],
  ["골프장", "golf course", "Noun", ["place"], "", "", "SUOBI09", "", ""],
  ["농구", "basketball", "Noun", ["activity", "sports"], "", "", "SUOBI09", "", ""],
  ["농구장", "basketball court", "Noun", ["place"], "", "", "SUOBI09", "", ""],
  ["서핑", "surfing", "Noun", ["activity"], "", "", "SUOBI09", "", ""],
  ["수영", "swimming", "Noun", ["activity"], "", "", "SUOBI09", "", ""],
  ["수영장", "swimming pool", "Noun", ["place"], "", "", "SUOBI09", "", ""],
  ["스노보드", "snowboard", "Noun", ["activity"], "", "", "SUOBI09", "", ""],
  ["스케이트", "skate", "Noun", ["activity"], "", "", "SUOBI09", "", ""],
  ["스케이트장", "skating rink", "Noun", ["place"], "", "", "SUOBI09", "", ""],
  ["스키", "ski", "Noun", ["activity"], "", "", "SUOBI09", "", ""],
  ["스키장", "ski resort", "Noun", ["place"], "", "", "SUOBI09", "", ""],
  ["요가", "yoga", "Noun", ["activity"], "", "", "SUOBI09", "", ""],
  ["지하철", "subway", "Noun", ["object", "transportation"], "", "", "SUOBI09", "", ""],
  ["탁구", "table tennis", "Noun", ["activity", "sports"], "", "", "SUOBI09", "", ""],
  ["탁구장", "table tennis room", "Noun", ["place"], "", "", "SUOBI09", "", ""],
  ["테니스", "tennis", "Noun", ["activity", "sports"], "", "", "SUOBI09", "", ""],
  ["테니스장", "tennis court", "Noun", ["place"], "", "", "SUOBI09", "", ""],
  ["비싸다", "to be expensive", "Descriptive Verb", ["descriptive_general", "descriptive_food"], "", "regular", "SUOBI09", "", ""],
  ["빌리다", "to borrow/rent", "Action Verb", ["transitive_general"], "", "regular", "SUOBI09", "", ""],
  ["빠르다", "to be fast", "Descriptive Verb", ["descriptive_general"], "", "reu_irregular", "SUOBI09", "", ""],
  ["잘하다", "to do well", "Action Verb", ["intransitive_general", "transitive_general"], "", "hada", "SUOBI09", "", ""],
  ["치다", "to hit", "Action Verb", ["transitive_sports"], "", "regular", "SUOBI09", "", ""],
  ["타다", "to ride", "Action Verb", ["transitive_transportation"], "", "regular", "SUOBI09", "", ""],
  ["등산하다", "to hike", "Action Verb", ["intransitive_general"], "", "hada", "SUOBI09", "", ""],
  ["청소하다", "to do cleaning", "Action Verb", ["intransitive_general", "transitive_place"], "", "hada", "SUOBI09", "", ""],
  ["너무", "too much", "Adverb", ["quantity"], "", "", "SUOBI09", "", ""],
  ["김치", "kimchi", "Noun", ["food"], "", "", "SUOBI09", "", ""],
  ["아이", "child", "Noun", ["person"], "", "", "SUOBI09", "", ""],
  ["한식", "Korean food", "Noun", ["food"], "", "", "SUOBI09", "", ""],
  ["데이트하다", "to go out with someone", "Action Verb", ["intransitive_general"], "", "hada", "SUOBI09", "", ""],
  ["빨래하다", "to do laundry", "Action Verb", ["intransitive_general"], "", "hada", "SUOBI09", "", ""],
  ["쇼핑하다", "to go shopping", "Action Verb", ["intransitive_general"], "", "hada", "SUOBI09", "", ""],
  ["여행하다", "to travel", "Action Verb", ["intransitive_general"], "", "hada", "SUOBI09", "", ""],
  ["많이", "much/many", "Adverb", ["quantity"], "", "", "SUOBI09", "", ""],
  ["아주", "very", "Adverb", ["degree"], "", "", "SUOBI09", "", ""],
  ["조금", "little/few", "Adverb", ["quantity"], "", "", "SUOBI09", "", ""],
  ["돕다", "to help", "Action Verb", ["transitive_person", "devtest"], "", "b_irregular", "SUOBI09", "", "", '{"domain":"action","req":"person","polarity":1}'],
  ["반갑다", "to be glad", "Descriptive Verb", ["descriptive_person"], "", "b_irregular", "SUOBI09", "", ""],
  ["쉽다", "to be easy", "Descriptive Verb", ["descriptive_general", "devtest"], "", "b_irregular", "SUOBI09", "", "", '{"domain":"state","req":"any","polarity":1}'],
  ["어렵다", "to be difficult", "Descriptive Verb", ["descriptive_general"], "", "b_irregular", "SUOBI09", "", ""],
  ["좁다", "to be narrow", "Descriptive Verb", ["descriptive_place", "devtest"], "", "regular", "SUOBI09", "", "", '{"domain":"state","req":"place","polarity":-1}'],

  // Grammar from SUOBI09
  ["~(으)세요", "polite imperative", "Grammar", ["imperative"], "", ["{AVst}으/세요"], "SUOBI09", "Polite Formal", ""],
  ["~고 싶다", "to want to", "Grammar", ["desire"], "", ["{VP_AVst}고 싶어요"], "SUOBI09", "", ""]
  ,

  // Vocabulary from SUOBI10
  ["공원", "park", "Noun", ["place"], "", "", "SUOBI10", "", ""],
  ["어제", "yesterday", "Noun", ["time"], "", "", "SUOBI10", "", ""],
  ["쉬다", "to rest", "Action Verb", ["intransitive_general"], "", "regular", "SUOBI10", "", ""],
  ["그제", "day before yesterday", "Noun", ["time"], "", "", "SUOBI10", "", ""],
  ["금년", "this year (sino)", "Noun", ["time"], "", "", "SUOBI10", "", ""],
  ["내년", "next year", "Noun", ["time"], "", "", "SUOBI10", "", ""],
  ["내일", "tomorrow", "Noun", ["time"], "", "", "SUOBI10", "", "", '{"domain":"time", "traits":["future"]}'],
  ["다음일", "next task", "Noun", ["event"], "", "", "SUOBI10", "", ""],
  ["다음", "next", "Noun", ["time_modifier", "time"], "", "", "SUOBI10", "", ""],
  ["달", "month/moon", "Noun", ["time"], "", "", "SUOBI10", "", ""],
  ["다음달", "next month", "Noun", ["time", "devtest"], "", "", "SUOBI10", "", "", '{"domain":"time"}'],
  ["다음주", "next week", "Noun", ["time"], "", "", "SUOBI10", "", ""],
  ["모레", "day after tomorrow", "Noun", ["time"], "", "", "SUOBI10", "", ""],
  ["올해", "this year", "Noun", ["time"], "", "", "SUOBI10", "", ""],
  ["이번", "this time", "Noun", ["time_modifier"], "", "", "SUOBI10", "", ""],
  ["작년", "last year (sino)", "Noun", ["time"], "", "", "SUOBI10", "", ""],
  ["지난해", "last year", "Noun", ["time"], "", "", "SUOBI10", "", ""],
  ["주", "week", "Noun", ["time"], "", "", "SUOBI10", "", ""],
  ["지난달", "last month", "Noun", ["time"], "", "", "SUOBI10", "", ""],
  ["지난주", "last week", "Noun", ["time"], "", "", "SUOBI10", "", ""],
  ["지난", "previous", "Noun", ["time_modifier"], "", "", "SUOBI10", "", ""],
  ["왜", "why", "Adverb", ["questionWord"], "", "", "SUOBI10", "", ""],
  ["콘서트", "concert", "Noun", ["event"], "", "", "SUOBI10", "", ""],
  ["표", "ticket", "Noun", ["object"], "", "", "SUOBI10", "", ""],
  ["예매하다", "to book", "Action Verb", ["transitive_general"], "", "hada", "SUOBI10", "", ""],
  ["일찍", "early", "Adverb", ["time"], "", "", "SUOBI10", "", ""],
  ["시간이 없다", "to have no time", "Descriptive Verb", ["descriptive_person"], "", "regular", "SUOBI10", "", ""],
  ["기차표", "train ticket", "Noun", ["object"], "", "", "SUOBI10", "", ""],
  ["병원", "hospital", "Noun", ["place"], "", "", "SUOBI10", "", ""],
  ["비행기 표", "plane ticket", "Noun", ["object"], "", "", "SUOBI10", "", ""],
  ["식당", "restaurant", "Noun", ["place"], "", "", "SUOBI10", "", ""],
  ["영화표", "movie ticket", "Noun", ["object"], "", "", "SUOBI10", "", ""],
  ["옷", "clothes", "Noun", ["object"], "", "", "SUOBI10", "", ""],
  ["호텔", "hotel", "Noun", ["place"], "", "", "SUOBI10", "", ""],
  ["늦다", "to be late", "Descriptive Verb", ["descriptive_general", "descriptive_person"], "", "regular", "SUOBI10", "", ""],
  ["아프다", "to be sick", "Descriptive Verb", ["descriptive_person"], "", "eu_irregular", "SUOBI10", "", ""],
  ["예약하다", "to make a reservation", "Action Verb", ["transitive_general", "transitive_place"], "", "hada", "SUOBI10", "", ""],
  ["늦게", "late", "Adverb", ["time"], "", "", "SUOBI10", "", ""],
  ["빨리", "quickly", "Adverb", ["time"], "", "", "SUOBI10", "", ""],
  ["천천히", "slowly", "Adverb", ["time"], "", "", "SUOBI10", "", ""],
  ["오래", "long", "Adverb", ["time"], "", "", "SUOBI10", "", ""],

  // Grammar from SUOBI10
  ["~아/어서", "because/and then", "Grammar", ["conjunction"], "", ["{VP_AVst}아/어서 {Clause}", "{VP_DVst}아/어서 {Clause}"], "SUOBI10", "", ""],
  ["~(으)ㄹ 거예요", "future tense", "Grammar", ["declarative", "future"], "", ["{AVst}으/ㄹ 거예요"], "SUOBI10", "Polite Informal", ""],
  ["~지만", "but/although", "Grammar", ["conjunction"], "", ["{VP_AVst}지만 {Clause}", "{VP_DVst}지만 {Clause}"], "SUOBI10", "", ""]
  ,

  // Vocabulary from SUOBI11
  ["약속", "appointment", "Noun", ["event"], "", "", "SUOBI11", "", ""],
  ["한강공원", "Hangang park", "Noun", ["place"], "", "", "SUOBI11", "", ""],
  ["가끔", "sometimes", "Adverb", ["frequency"], "", "", "SUOBI11", "", "", '{"logic":"frequency", "traits":["low"]}'],
  ["요즘", "these days", "Noun", ["time"], "", "", "SUOBI11", "", ""],
  ["자전거를 타다", "to ride a bicycle", "Action Verb", ["intransitive_general"], "", "regular", "SUOBI11", "", ""],
  ["약속 시간", "appointment time", "Noun", ["time"], "", "", "SUOBI11", "", ""],
  ["약속 장소", "appointment place", "Noun", ["place"], "", "", "SUOBI11", "", ""],
  ["약속을 지키다", "to keep appointment", "Action Verb", ["intransitive_general"], "", "regular", "SUOBI11", "", ""],
  ["약속을 하다", "to make appointment", "Action Verb", ["intransitive_general"], "", "hada", "SUOBI11", "", ""],
  ["약속이 없다", "to not have appointment", "Descriptive Verb", ["descriptive_person"], "", "regular", "SUOBI11", "", ""],
  ["약속이 있다", "to have appointment", "Descriptive Verb", ["descriptive_person"], "", "regular", "SUOBI11", "", ""],
  ["날마다", "everyday", "Adverb", ["frequency"], "", "", "SUOBI11", "", ""],
  ["놀이공원", "amusement park", "Noun", ["place"], "", "", "SUOBI11", "", ""],
  ["드라마", "drama", "Noun", ["object"], "", "", "SUOBI11", "", ""],
  ["심심하다", "to be bored", "Descriptive Verb", ["descriptive_person"], "", "hada", "SUOBI11", "", ""],
  ["글쎄요", "well", "Exclamation", ["interjection"], "", "", "SUOBI11", "", ""],
  ["극장", "theater", "Noun", ["place"], "", "", "SUOBI11", "", ""],
  ["동물원", "zoo", "Noun", ["place"], "", "", "SUOBI11", "", ""],
  ["미술관", "art gallery", "Noun", ["place"], "", "", "SUOBI11", "", ""],
  ["박물관", "museum", "Noun", ["place"], "", "", "SUOBI11", "", ""],
  ["영화관", "movie theater", "Noun", ["place"], "", "", "SUOBI11", "", ""],
  ["카페", "cafe", "Noun", ["place"], "", "", "SUOBI11", "", ""],

  // Grammar from SUOBI11
  ["~(으)ㄹ게요", "I will", "Grammar", ["declarative", "promise"], "", ["{AVst}으/ㄹ게요"], "SUOBI11", "Polite Informal", ""],
  ["~(으)러 가다/오다", "go/come to do", "Grammar", ["purpose"], "", ["{AVst}으/러 가요", "{AVst}으/러 와요"], "SUOBI11", "", ""],

  // Vocabulary from SUOBI12
  ["교수", "professor", "Noun", ["person", "job"], "", "", "SUOBI12", "", ""],
  ["대학교", "college", "Noun", ["place"], "", "", "SUOBI12", "", ""],
  ["아버지", "father", "Noun", ["person", "family"], "", "", "SUOBI12", "", ""],
  ["역사", "history", "Noun", ["concept"], "", "", "SUOBI12", "", ""],
  ["이분", "this person", "Pronoun", ["person", "demonstrative"], "", "", "SUOBI12", "", ""],
  ["남동생", "younger brother", "Noun", ["person", "family"], "", "", "SUOBI12", "", ""],
  ["누나", "older sister (for male)", "Noun", ["person", "family"], "", "", "SUOBI12", "", ""],
  ["부모님", "parents", "Noun", ["person", "family"], "", "", "SUOBI12", "", ""],
  ["어머니", "mother", "Noun", ["person", "family"], "", "", "SUOBI12", "", ""],
  ["언니", "older sister (for female)", "Noun", ["person", "family"], "", "", "SUOBI12", "", ""],
  ["여동생", "younger sister", "Noun", ["person", "family"], "", "", "SUOBI12", "", ""],
  ["오빠", "older brother (for female)", "Noun", ["person", "family"], "", "", "SUOBI12", "", ""],
  ["외할머니", "grandmother (mother's side)", "Noun", ["person", "family"], "", "", "SUOBI12", "", ""],
  ["외할아버지", "grandfather (mother's side)", "Noun", ["person", "family"], "", "", "SUOBI12", "", ""],
  ["할머니", "grandmother", "Noun", ["person", "family"], "", "", "SUOBI12", "", ""],
  ["할아버지", "grandfather", "Noun", ["person", "family"], "", "", "SUOBI12", "", ""],
  ["형", "older brother (for male)", "Noun", ["person", "family"], "", "", "SUOBI12", "", ""],
  ["형제", "sibling", "Noun", ["person", "family"], "", "", "SUOBI12", "", ""],
  ["계시다", "to be", "Action Verb", ["intransitive_motion", "intransitive_general"], "", "regular", "SUOBI12", "", ""],
  ["드시다", "to eat/drink", "Action Verb", ["transitive_food", "transitive_drink"], "", "regular", "SUOBI12", "", ""],
  ["말씀하시다", "to speak", "Action Verb", ["intransitive_general"], "", "regular", "SUOBI12", "", ""],
  ["잡수시다", "to eat", "Action Verb", ["transitive_food"], "", "regular", "SUOBI12", "", ""],
  ["주무시다", "to sleep", "Action Verb", ["intransitive_general"], "", "regular", "SUOBI12", "", ""],
  ["과자", "cookie", "Noun", ["food"], "", "", "SUOBI12", "", ""],
  ["뭐", "what", "Pronoun", ["questionWord", "object"], "", "", "SUOBI12", "", ""],
  ["요리", "dish", "Noun", ["food", "activity"], "", "", "SUOBI12", "", ""],
  ["와", "wow", "Exclamation", ["interjection"], "", "", "SUOBI12", "", ""],
  ["구경하다", "to look around", "Action Verb", ["transitive_general", "transitive_place"], "", "hada", "SUOBI12", "", ""],
  ["누구", "who", "Pronoun", ["questionWord", "person"], "", "", "SUOBI12", "", "", '{"domain":"person", "traits":["question"]}'],
  ["무엇", "what", "Pronoun", ["questionWord", "object"], "", "", "SUOBI12", "", "", '{"domain":"object", "traits":["question"]}'],
  ["이거", "this (thing)", "Pronoun", ["demonstrative", "object"], "", "", "SUOBI12", "", ""],
  ["그림을 그리다", "to draw a picture", "Action Verb", ["intransitive_general"], "", "regular", "SUOBI12", "", ""],
  ["독서를 하다", "to read", "Action Verb", ["intransitive_general"], "", "hada", "SUOBI12", "", ""],
  ["사진을 찍다", "to take a photo", "Action Verb", ["intransitive_general"], "", "regular", "SUOBI12", "", ""],
  ["요리를 하다", "to cook", "Action Verb", ["intransitive_general"], "", "hada", "SUOBI12", "", ""],
  ["춤을 추다", "to dance", "Action Verb", ["intransitive_general"], "", "regular", "SUOBI12", "", ""],

  // Grammar from SUOBI12
  ["~(으)ㄹ 수 있다", "can do", "Grammar", ["ability"], "", ["{AVst}으/ㄹ 수 있어요"], "SUOBI12", "", ""],
  ["~(으)ㄹ 수 없다", "cannot do", "Grammar", ["inability"], "", ["{AVst}으/ㄹ 수 없어요"], "SUOBI12", "", ""],
  ["못 ~ / ~지 못하다", "cannot do (external)", "Grammar", ["inability"], "", ["못 {AVst}아/어요", "{AVst}지 못해요"], "SUOBI12", "", ""]
  ,

  // Vocabulary from SUOBI13
  ["얼마", "how much/many", "Pronoun", ["questionWord", "quantity"], "", "", "SUOBI13", "", ""],
  ["원", "won", "Noun", ["measureWord"], "", "", "SUOBI13", "", ""],
  ["치마", "skirt", "Noun", ["object", "clothes"], "", "", "SUOBI13", "", ""],
  ["그래요", "yes, it is", "Exclamation", ["greeting"], "", "", "SUOBI13", "", ""],
  ["짧다", "to be short", "Descriptive Verb", ["descriptive_general"], "", "regular", "SUOBI13", "", ""],
  ["더", "more", "Adverb", ["degree"], "", "", "SUOBI13", "", ""],
  ["만", "ten thousand", "Noun", ["number", "sinoNumber"], "", "", "SUOBI13", "", ""],
  ["값", "price", "Noun", ["attribute", "devtest"], "", "", "SUOBI13", "", "", '{"domain":"attribute"}'],
  ["구두", "dress shoes", "Noun", ["object", "shoes"], "", "", "SUOBI13", "", ""],
  ["바지", "pants", "Noun", ["object", "clothes"], "", "", "SUOBI13", "", ""],
  ["백", "hundred", "Noun", ["number", "sinoNumber"], "", "", "SUOBI13", "", ""],
  ["슬리퍼", "slippers", "Noun", ["object", "shoes"], "", "", "SUOBI13", "", ""],
  ["신발", "shoes", "Noun", ["object", "shoes"], "", "", "SUOBI13", "", ""],
  ["십만", "hundred thousand", "Noun", ["number", "sinoNumber"], "", "", "SUOBI13", "", ""],
  ["와이셔츠", "collared shirt", "Noun", ["object", "clothes"], "", "", "SUOBI13", "", ""],
  ["우산", "umbrella", "Noun", ["object"], "", "", "SUOBI13", "", ""],
  ["운동화", "sneakers", "Noun", ["object", "shoes"], "", "", "SUOBI13", "", ""],
  ["천", "thousand", "Noun", ["number", "sinoNumber"], "", "", "SUOBI13", "", ""],
  ["코트", "coat", "Noun", ["object", "clothes"], "", "", "SUOBI13", "", ""],
  ["티셔츠", "t-shirt", "Noun", ["object", "clothes"], "", "", "SUOBI13", "", ""],
  ["가볍다", "to be light", "Descriptive Verb", ["descriptive_general"], "", "b_irregular", "SUOBI13", "", ""],
  ["두껍다", "to be thick", "Descriptive Verb", ["descriptive_general"], "", "b_irregular", "SUOBI13", "", ""],
  ["무겁다", "to be heavy", "Descriptive Verb", ["descriptive_general"], "", "b_irregular", "SUOBI13", "", ""],
  ["싸다", "to be cheap", "Descriptive Verb", ["descriptive_general", "descriptive_food"], "", "regular", "SUOBI13", "", ""],
  ["얇다", "to be thin", "Descriptive Verb", ["descriptive_general"], "", "regular", "SUOBI13", "", ""],
  ["들", "plural suffix", "Noun", ["plural"], "", "", "SUOBI13", "", ""],
  ["송이", "cluster", "Noun", ["measureWord"], "", "", "SUOBI13", "", ""],
  ["스물", "twenty", "Noun", ["number", "koreanNumber"], "", "", "SUOBI13", "", ""],
  ["장미", "rose", "Noun", ["object", "flower"], "", "", "SUOBI13", "", ""],
  ["찾다", "to find", "Action Verb", ["transitive_general"], "", "regular", "SUOBI13", "", ""],
  ["제일", "most", "Adverb", ["degree"], "", "", "SUOBI13", "", ""],
  ["어서 오세요", "welcome", "Exclamation", ["greeting"], "", "", "SUOBI13", "", ""],
  ["가게", "store", "Noun", ["place"], "", "", "SUOBI13", "", ""],
  ["곳", "place", "Noun", ["place"], "", "", "SUOBI13", "", ""],
  ["면세점", "duty free shop", "Noun", ["place"], "", "", "SUOBI13", "", ""],
  ["바나나", "banana", "Noun", ["food", "fruit"], "", "", "SUOBI13", "", ""],
  ["백화점", "department store", "Noun", ["place"], "", "", "SUOBI13", "", ""],
  ["슈퍼마켓", "supermarket", "Noun", ["place"], "", "", "SUOBI13", "", ""],
  ["시장", "market", "Noun", ["place"], "", "", "SUOBI13", "", ""],
  ["양말", "socks", "Noun", ["object", "clothes"], "", "", "SUOBI13", "", ""],
  ["주스", "juice", "Noun", ["drink"], "", "", "SUOBI13", "", ""],
  ["크림빵", "cream bread", "Noun", ["food"], "", "", "SUOBI13", "", ""],
  ["권", "counting word for books", "Noun", ["measureWord"], "", "", "SUOBI13", "", ""],
  ["벌", "counting word for clothes", "Noun", ["measureWord"], "", "", "SUOBI13", "", ""],
  ["자루", "counting word for pen/pencil", "Noun", ["measureWord"], "", "", "SUOBI13", "", ""],
  ["장", "counting word for paper", "Noun", ["measureWord"], "", "", "SUOBI13", "", ""],
  ["켤레", "counting word for shoes/socks", "Noun", ["measureWord"], "", "", "SUOBI13", "", ""],

  // Grammar from SUOBI13
  ["~아/어도 되다", "may I / it is okay to", "Grammar", ["permission"], "", ["{AVst}아/어도 돼요"], "SUOBI13", "", ""],
  ["~(으)면 안 되다", "must not", "Grammar", ["prohibition"], "", ["{AVst}으/면 안 돼요"], "SUOBI13", "", ""],
  ["~아/어야 하다/되다", "must / have to do", "Grammar", ["obligation"], "", ["{AVst}아/어야 해요", "{AVst}아/어야 돼요"], "SUOBI13", "", ""],

  // Vocabulary from SUOBI14
  ["모두", "all", "Adverb", ["quantity"], "", "", "SUOBI14", "", ""],
  ["선물", "gift", "Noun", ["object"], "", "", "SUOBI14", "", ""],
  ["케이크", "cake", "Noun", ["food"], "", "", "SUOBI14", "", ""],
  ["화장품", "cosmetics", "Noun", ["object"], "", "", "SUOBI14", "", ""],
  ["선물하다", "to give a gift", "Action Verb", ["transitive_general", "transitive_person"], "", "hada", "SUOBI14", "", ""],
  ["이따가", "later", "Adverb", ["time"], "", "", "SUOBI14", "", ""],
  ["것", "thing", "Noun", ["object"], "", "", "SUOBI14", "", ""],
  ["꽃다발", "bouquet", "Noun", ["object", "flower"], "", "", "SUOBI14", "", ""],
  ["넥타이", "tie", "Noun", ["object", "clothes"], "", "", "SUOBI14", "", ""],
  ["상품권", "gift certificate", "Noun", ["object"], "", "", "SUOBI14", "", ""],
  ["생신", "birthday (honorific)", "Noun", ["time", "event"], "", "", "SUOBI14", "", ""],
  ["시디", "CD", "Noun", ["object"], "", "", "SUOBI14", "", ""],
  ["액세서리", "accessories", "Noun", ["object", "clothes"], "", "", "SUOBI14", "", ""],
  ["이메일", "e-mail", "Noun", ["object"], "", "", "SUOBI14", "", ""],
  ["인형", "doll", "Noun", ["object"], "", "", "SUOBI14", "", ""],
  ["향수", "perfume", "Noun", ["object"], "", "", "SUOBI14", "", ""],
  ["드리다", "to give (honorific)", "Action Verb", ["transitive_general", "transitive_person"], "", "regular", "SUOBI14", "", ""],
  ["말씀드리다", "to say (honorific)", "Action Verb", ["intransitive_general", "transitive_person"], "", "regular", "SUOBI14", "", ""],
  ["말하다", "to say", "Action Verb", ["intransitive_general", "transitive_person"], "", "hada", "SUOBI14", "", ""],
  ["보내다", "to send", "Action Verb", ["transitive_general", "transitive_person"], "", "regular", "SUOBI14", "", ""],
  ["연락드리다", "to contact (honorific)", "Action Verb", ["transitive_person"], "", "regular", "SUOBI14", "", ""],
  ["연락하다", "to contact", "Action Verb", ["transitive_person"], "", "hada", "SUOBI14", "", ""],
  ["인사드리다", "to greet (honorific)", "Action Verb", ["transitive_person"], "", "regular", "SUOBI14", "", ""],
  ["인사하다", "to greet", "Action Verb", ["transitive_person"], "", "hada", "SUOBI14", "", ""],
  ["전화드리다", "to call (honorific)", "Action Verb", ["transitive_person"], "", "regular", "SUOBI14", "", ""],
  ["전화하다", "to call", "Action Verb", ["transitive_person"], "", "hada", "SUOBI14", "", ""],
  ["그렇지만", "however", "Adverb", ["conjunction"], "", "", "SUOBI14", "", ""],
  ["그래서", "so", "Adverb", ["conjunction"], "", "", "SUOBI14", "", ""],
  ["초콜릿", "chocolate", "Noun", ["food"], "", "", "SUOBI14", "", ""],
  ["고르다", "to pick/select", "Action Verb", ["transitive_general"], "", "reu_irregular", "SUOBI14", "", ""],
  ["준비하다", "to prepare", "Action Verb", ["transitive_general"], "", "hada", "SUOBI14", "", ""],
  ["축하하다", "to congratulate", "Action Verb", ["transitive_person"], "", "hada", "SUOBI14", "", ""],
  ["정말", "really", "Adverb", ["degree"], "", "", "SUOBI14", "", ""],
  ["여기저기", "here and there", "Noun", ["place"], "", "", "SUOBI14", "", ""],
  ["생일축하 노래를 부르다", "to sing a birthday song", "Action Verb", ["intransitive_general"], "", "reu_irregular", "SUOBI14", "", ""],
  ["선물을 고르다", "to pick a gift", "Action Verb", ["intransitive_general"], "", "reu_irregular", "SUOBI14", "", ""],
  ["카드를 쓰다", "to write a card", "Action Verb", ["intransitive_general"], "", "eu_irregular", "SUOBI14", "", ""],
  ["케이크를 자르다", "to cut cake", "Action Verb", ["intransitive_general"], "", "reu_irregular", "SUOBI14", "", ""],
  ["풍선을 불다", "to blow a balloon", "Action Verb", ["intransitive_general"], "", "l_irregular", "SUOBI14", "", ""],
  ["다르다", "to be different", "Descriptive Verb", ["descriptive_general"], "", "reu_irregular", "SUOBI14", "", ""],
  ["모르다", "to not know", "Action Verb", ["transitive_general"], "", "reu_irregular", "SUOBI14", "", ""],
  ["부르다", "to sing", "Action Verb", ["transitive_general"], "", "reu_irregular", "SUOBI14", "", ""],
  ["자르다", "to cut", "Action Verb", ["transitive_general"], "", "reu_irregular", "SUOBI14", "", ""],
  ["에게/한테", "to/for", "Grammar", ["particle"], "", ["{N:person}에게", "{N:person}한테"], "SUOBI14", "", ""],

  // Grammar from SUOBI14
  ["~(으)면", "if/when", "Grammar", ["condition", "devtest"], "", ["{VP_AVst}으/면 {Clause}", "{VP_DVst}으/면 {Clause}"], "SUOBI14", "", "", '{"logic":"condition"}'],
  ["~는데", "but/and", "Grammar", ["conjunction", "devtest"], "", ["{VP_AVst}는데 {Clause}"], "SUOBI14", "", "", '{"logic":"contrast","polarity_match":false}'],
  ["~(으)ㄴ데", "but/and", "Grammar", ["conjunction", "devtest"], "", ["{VP_DVst}으/ㄴ데 {Clause}"], "SUOBI14", "", "", '{"logic":"contrast","polarity_match":false}']
  ,

  // Vocabulary from SUOBI15
  ["전화번호", "phone number", "Noun", ["object"], "", "", "SUOBI15", "", ""],
  ["잠깐만요", "one moment", "Exclamation", ["interjection"], "", "", "SUOBI15", "", ""],
  ["국가 번호", "country code", "Noun", ["object"], "", "", "SUOBI15", "", ""],
  ["지역 번호", "area code", "Noun", ["object"], "", "", "SUOBI15", "", ""],
  ["휴대전화", "mobile phone", "Noun", ["object"], "", "", "SUOBI15", "", "", '{"domain":"object"}'],
  ["이야기", "story", "Noun", ["object"], "", "", "SUOBI15", "", ""],
  ["파티", "party", "Noun", ["event"], "", "", "SUOBI15", "", ""],
  ["여보세요", "hello", "Exclamation", ["greeting"], "", "", "SUOBI15", "", ""],
  ["전화를 받다", "to receive a call", "Action Verb", ["intransitive_general"], "", "regular", "SUOBI15", "", ""],
  ["뉴스", "news", "Noun", ["object"], "", "", "SUOBI15", "", ""],
  ["통화중이다", "in the middle of a phone call", "Descriptive Verb", ["descriptive_general"], "", "regular", "SUOBI15", "", ""],
  ["문자메시지를 받다", "to receive a text message", "Action Verb", ["intransitive_general"], "", "regular", "SUOBI15", "", ""],
  ["문자메시지를 보내다", "to send a text message", "Action Verb", ["intransitive_general"], "", "regular", "SUOBI15", "", ""],
  ["전화가 오다", "call is coming", "Action Verb", ["intransitive_general"], "", "regular", "SUOBI15", "", ""],
  ["전화를 걸다", "to make a call", "Action Verb", ["intransitive_general"], "", "l_irregular", "SUOBI15", "", ""],
  ["전화를 끊다", "to hang up a call", "Action Verb", ["intransitive_general"], "", "regular", "SUOBI15", "", ""],
  ["전화를 바꾸다", "to put someone else on the phone", "Action Verb", ["intransitive_general"], "", "regular", "SUOBI15", "", ""],
  ["진지", "meal (honorific)", "Noun", ["food"], "", "", "SUOBI15", "", ""],
  ["연세", "age (honorific)", "Noun", ["attribute"], "", "", "SUOBI15", "", ""],
  ["성함", "name (honorific)", "Noun", ["attribute"], "", "", "SUOBI15", "", ""],
  ["댁", "house (honorific)", "Noun", ["place"], "", "", "SUOBI15", "", ""],
  ["여쭙다", "to ask (honorific)", "Action Verb", ["transitive_general", "transitive_person"], "", "b_irregular", "SUOBI15", "", ""],

  // Grammar from SUOBI15
  ["~(으)ㄴ", "relative clause (verb past / adjective present)", "Grammar", ["modifier", "devtest"], "", ["{AVst}으/ㄴ {N:place}", "{DVst}으/ㄴ {N:place}"], "SUOBI15", "", "", '{"logic":"modifier"}'],
  ["~는", "relative clause (verb present)", "Grammar", ["modifier", "devtest"], "", ["{AVst}는 {N:place}"], "SUOBI15", "", "", '{"logic":"modifier"}'],
  ["~(으)ㄹ", "relative clause (future)", "Grammar", ["modifier", "devtest"], "", ["{AVst}으/ㄹ {N:place}"], "SUOBI15", "", "", '{"logic":"modifier"}'],
  ["께", "to/for (honorific)", "Grammar", ["particle"], "", ["{N:person}께"], "SUOBI15", "", ""],
  ["께서", "subject marker (honorific)", "Grammar", ["particle"], "", ["{N:person}께서"], "SUOBI15", "", ""],

  // Vocabulary from SUOBI16
  ["택시", "taxi", "Noun", ["transportation"], "", "", "SUOBI16", "", ""],
  ["가깝다", "to be close", "Descriptive Verb", ["descriptive_place"], "", "b_irregular", "SUOBI16", "", ""],
  ["걸리다", "to take (time)", "Action Verb", ["intransitive_general"], "", "regular", "SUOBI16", "", ""],
  ["얼마나", "how much/long", "Adverb", ["quantity"], "", "", "SUOBI16", "", ""],
  ["쯤", "about/approximately", "Noun", ["particle"], "", "", "SUOBI16", "", ""],
  ["고속버스", "express bus", "Noun", ["transportation"], "", "", "SUOBI16", "", ""],
  ["공항버스", "airport bus", "Noun", ["transportation"], "", "", "SUOBI16", "", ""],
  ["기차", "train", "Noun", ["transportation"], "", "", "SUOBI16", "", ""],
  ["배", "ship", "Noun", ["transportation"], "", "", "SUOBI16", "", ""],
  ["버스", "bus", "Noun", ["transportation"], "", "", "SUOBI16", "", ""],
  ["비행기", "airplane", "Noun", ["transportation"], "", "", "SUOBI16", "", ""],
  ["오토바이", "motorcycle", "Noun", ["transportation"], "", "", "SUOBI16", "", ""],
  ["자전거", "bicycle", "Noun", ["transportation"], "", "", "SUOBI16", "", ""],
  ["젓가락", "chopsticks", "Noun", ["object"], "", "", "SUOBI16", "", ""],
  ["종업원", "employee", "Noun", ["person", "job"], "", "", "SUOBI16", "", ""],
  ["시간", "hour/time", "Noun", ["time"], "", "", "SUOBI16", "", ""],
  ["호선", "subway line", "Noun", ["attribute"], "", "", "SUOBI16", "", ""],
  ["내리다", "to get off", "Action Verb", ["intransitive_general"], "", "regular", "SUOBI16", "", ""],
  ["어떻게", "how", "Adverb", ["questionWord"], "", "", "SUOBI16", "", ""],
  ["고속버스터미널", "express bus terminal", "Noun", ["place"], "", "", "SUOBI16", "", ""],
  ["공항", "airport", "Noun", ["place"], "", "", "SUOBI16", "", ""],
  ["역", "station", "Noun", ["place"], "", "", "SUOBI16", "", ""],
  ["정류장", "bus stop", "Noun", ["place"], "", "", "SUOBI16", "", ""],
  ["갈아타다", "to transfer", "Action Verb", ["transitive_transportation"], "", "regular", "SUOBI16", "", ""],
  ["끄다", "to turn off", "Action Verb", ["transitive_general"], "", "eu_irregular", "SUOBI16", "", ""],
  ["도착하다", "to arrive", "Action Verb", ["intransitive_place"], "", "hada", "SUOBI16", "", ""],
  ["출발하다", "to depart", "Action Verb", ["intransitive_place"], "", "hada", "SUOBI16", "", ""],
  ["번", "number", "Noun", ["attribute"], "", "", "SUOBI16", "", ""],

  // Grammar from SUOBI16
  ["~(으)시~", "honorific infix", "Grammar", ["honorific", "devtest"], "", ["{AVst}으/십니다", "{AVst}으/셔요"], "SUOBI16", "", "", '{"logic":"honorific"}'],
  ["~(으)ㄴ 적이 있다/없다", "have experience of", "Grammar", ["experience"], "", ["{AVst}으/ㄴ 적이 있어요", "{AVst}으/ㄴ 적이 없어요"], "SUOBI16", "", ""],
  ["보다 (더)", "more than", "Grammar", ["particle"], "", ["{N:place}보다 {DVst}아/어요"], "SUOBI16", "", ""]
  ,

  // Vocabulary from SUOBI17
  ["미터", "meter", "Noun", ["measureWord"], "", "", "SUOBI17", "", ""],
  ["사거리", "4 way intersection", "Noun", ["place"], "", "", "SUOBI17", "", ""],
  ["약국", "pharmacy", "Noun", ["place"], "", "", "SUOBI17", "", ""],
  ["오른쪽", "right side", "Noun", ["direction"], "", "", "SUOBI17", "", ""],
  ["실례지만", "excuse me", "Exclamation", ["greeting"], "", "", "SUOBI17", "", ""],
  ["저", "uhm", "Exclamation", ["interjection"], "", "", "SUOBI17", "", "", '{"domain":"person", "traits":["first_person", "humble"]}'],
  ["그쪽", "your side", "Noun", ["direction", "demonstrative"], "", "", "SUOBI17", "", ""],
  ["왼쪽", "left side", "Noun", ["direction"], "", "", "SUOBI17", "", ""],
  ["이쪽", "this side", "Noun", ["direction", "demonstrative"], "", "", "SUOBI17", "", ""],
  ["저쪽", "that side", "Noun", ["direction", "demonstrative"], "", "", "SUOBI17", "", ""],
  ["지하", "basement", "Noun", ["place"], "", "", "SUOBI17", "", ""],
  ["층", "floor", "Noun", ["measureWord", "attribute"], "", "", "SUOBI17", "", ""],
  ["한복", "hanbok", "Noun", ["object", "clothes"], "", "", "SUOBI17", "", ""],
  ["물어보다", "to ask", "Action Verb", ["transitive_general", "transitive_person"], "", "regular", "SUOBI17", "", ""],
  ["똑바로", "straight", "Adverb", ["direction"], "", "", "SUOBI17", "", ""],
  ["거기", "there", "Noun", ["place", "demonstrative"], "", "", "SUOBI17", "", ""],
  ["건너편", "the other side", "Noun", ["place"], "", "", "SUOBI17", "", ""],
  ["횡단보도", "crosswalk", "Noun", ["place"], "", "", "SUOBI17", "", ""],
  ["건너다", "to cross", "Action Verb", ["intransitive_place"], "", "regular", "SUOBI17", "", ""],
  ["보이다", "to be seen", "Action Verb", ["intransitive_general"], "", "regular", "SUOBI17", "", ""],
  ["약", "medicine", "Noun", ["object"], "", "", "SUOBI17", "", ""],
  ["육교", "pedestrian overpass", "Noun", ["place"], "", "", "SUOBI17", "", ""],
  ["지하도", "underpass", "Noun", ["place"], "", "", "SUOBI17", "", ""],
  ["출구", "exit", "Noun", ["place"], "", "", "SUOBI17", "", ""],
  ["화장실", "restroom", "Noun", ["place"], "", "", "SUOBI17", "", ""],
  ["나가다", "to exit", "Action Verb", ["intransitive_motion", "intransitive_place"], "", "regular", "SUOBI17", "", ""],
  ["내려가다", "to go down", "Action Verb", ["intransitive_motion", "intransitive_place"], "", "regular", "SUOBI17", "", ""],
  ["들어가다", "to enter", "Action Verb", ["intransitive_motion", "intransitive_place"], "", "regular", "SUOBI17", "", ""],
  ["올라가다", "to go up", "Action Verb", ["intransitive_motion", "intransitive_place"], "", "regular", "SUOBI17", "", ""],

  // Grammar from SUOBI17
  ["~(으)ㄴ 후에 / ~기 전에", "after / before doing", "Grammar", ["time_clause"], "", ["{AVst}으/ㄴ 후에 {Clause}", "{AVst}기 전에 {Clause}"], "SUOBI17", "", ""],
  ["~(으)면서", "while doing", "Grammar", ["conjunction", "devtest"], "", ["{AVst}으/면서 {Clause}"], "SUOBI17", "", "", '{"logic":"parallel"}'],

  // Vocabulary from SUOBI18
  ["일기예보", "weather forecast", "Noun", ["information"], "", "", "SUOBI18", "", ""],
  ["따뜻하다", "to be warm", "Descriptive Verb", ["descriptive_general", "weather"], "", "hada", "SUOBI18", "", ""],
  ["가지고 오다", "to bring", "Action Verb", ["transitive_general"], "", "regular", "SUOBI18", "", ""],
  ["비가 오다", "it's raining", "Action Verb", ["intransitive_general", "weather"], "", "regular", "SUOBI18", "", ""],
  ["우산을 쓰다", "to use an umbrella", "Action Verb", ["intransitive_general"], "", "eu_irregular", "SUOBI18", "", ""],
  ["물건", "object", "Noun", ["object"], "", "", "SUOBI18", "", ""],
  ["맑다", "to be clear", "Descriptive Verb", ["descriptive_general", "weather"], "", "regular", "SUOBI18", "", ""],
  ["선선하다", "to be cool", "Descriptive Verb", ["descriptive_general", "weather"], "", "hada", "SUOBI18", "", ""],
  ["쌀쌀하다", "to be chilly", "Descriptive Verb", ["descriptive_general", "weather"], "", "hada", "SUOBI18", "", ""],
  ["흐리다", "to be cloudy", "Descriptive Verb", ["descriptive_general", "weather"], "", "regular", "SUOBI18", "", ""],
  ["눈이 오다", "it's snowing", "Action Verb", ["intransitive_general", "weather"], "", "regular", "SUOBI18", "", ""],
  ["바람이 불다", "wind is blowing", "Action Verb", ["intransitive_general", "weather"], "", "l_irregular", "SUOBI18", "", ""],
  ["벚꽃", "cherry blossom", "Noun", ["object", "flower"], "", "", "SUOBI18", "", ""],
  ["봄", "spring", "Noun", ["time", "season"], "", "", "SUOBI18", "", ""],
  ["피다", "to blossom", "Action Verb", ["intransitive_general"], "", "regular", "SUOBI18", "", ""],
  ["소풍을 가다", "to go on a picnic", "Action Verb", ["intransitive_general"], "", "regular", "SUOBI18", "", ""],
  ["계절", "season", "Noun", ["time", "season"], "", "", "SUOBI18", "", ""],
  ["눈사람", "snowman", "Noun", ["object"], "", "", "SUOBI18", "", ""],
  ["팝콘", "popcorn", "Noun", ["food"], "", "", "SUOBI18", "", ""],
  ["눈싸움을 하다", "to snowfight", "Action Verb", ["intransitive_general"], "", "hada", "SUOBI18", "", ""],
  ["단풍 구경을 하다", "to see autumn leaves", "Action Verb", ["intransitive_general"], "", "hada", "SUOBI18", "", ""],
  ["담배를 피우다", "to smoke a cigarette", "Action Verb", ["intransitive_general"], "", "regular", "SUOBI18", "", ""],
  ["해수욕장에 가다", "to go to a beach", "Action Verb", ["intransitive_general"], "", "regular", "SUOBI18", "", ""],
  ["여름", "summer", "Noun", ["time", "season"], "", "", "SUOBI18", "", ""],
  ["가을", "autumn", "Noun", ["time", "season"], "", "", "SUOBI18", "", ""],
  ["겨울", "winter", "Noun", ["time", "season"], "", "", "SUOBI18", "", ""],

  // Grammar from SUOBI18
  ["~기 / ~는 것", "doing", "Grammar", ["modifier", "gerund", "devtest"], "", ["{AVst}기", "{AVst}는 것"], "SUOBI18", "", "", '{"logic":"gerund"}']
  ,

  // Vocabulary from SUOBI19
  ["민박집", "bed and breakfast", "Noun", ["place"], "", "", "SUOBI19", "", ""],
  ["전주", "Jeonju", "Noun", ["place"], "", "", "SUOBI19", "", ""],
  ["민박하다", "to stay at bed and breakfast", "Action Verb", ["intransitive_place"], "", "hada", "SUOBI19", "", ""],
  ["아직", "not yet", "Adverb", ["time"], "", "", "SUOBI19", "", ""],
  ["게스트하우스", "guesthouse", "Noun", ["place"], "", "", "SUOBI19", "", ""],
  ["여행", "travel", "Noun", ["activity", "event"], "", "", "SUOBI19", "", ""],
  ["여행사", "travel agency", "Noun", ["place"], "", "", "SUOBI19", "", ""],
  ["콘도", "condo", "Noun", ["place"], "", "", "SUOBI19", "", ""],
  ["펜션", "rental cottage", "Noun", ["place"], "", "", "SUOBI19", "", ""],
  ["계획을 세우다", "to make a plan", "Action Verb", ["intransitive_general"], "", "regular", "SUOBI19", "", ""],
  ["여행을 가다", "to go on a trip", "Action Verb", ["intransitive_general"], "", "regular", "SUOBI19", "", ""],
  ["모자", "hat", "Noun", ["object", "clothes"], "", "", "SUOBI19", "", ""],
  ["떠나다", "to leave", "Action Verb", ["intransitive_place"], "", "regular", "SUOBI19", "", ""],
  ["다", "all", "Adverb", ["quantity"], "", "", "SUOBI19", "", ""],
  ["선글라스", "sunglasses", "Noun", ["object", "clothes"], "", "", "SUOBI19", "", ""],
  ["여권", "passport", "Noun", ["object"], "", "", "SUOBI19", "", ""],
  ["충전기", "charger", "Noun", ["object"], "", "", "SUOBI19", "", ""],
  ["신다", "to wear (shoes)", "Action Verb", ["transitive_clothes"], "", "regular", "SUOBI19", "", ""],
  ["쓰다", "to wear on head", "Action Verb", ["transitive_clothes", "transitive_general"], "", "eu_irregular", "SUOBI19", "", ""],
  ["돈을 바꾸다", "to exchange money", "Action Verb", ["intransitive_general"], "", "regular", "SUOBI19", "", ""],

  // Vocabulary from SUOBI20
  ["학기", "semester", "Noun", ["time"], "", "", "SUOBI20", "", ""],
  ["돌아오다", "to come back", "Action Verb", ["intransitive_place"], "", "regular", "SUOBI20", "", ""],
  ["방학하다", "to vacation", "Action Verb", ["intransitive_general"], "", "hada", "SUOBI20", "", ""],
  ["시작되다", "to be started", "Action Verb", ["intransitive_general"], "", "regular", "SUOBI20", "", ""],
  ["한번", "once", "Noun", ["time"], "", "", "SUOBI20", "", ""],
  ["끝", "end", "Noun", ["time", "event"], "", "", "SUOBI20", "", ""],
  ["방학", "vacation", "Noun", ["time", "event"], "", "", "SUOBI20", "", ""],
  ["방학중", "during vacation", "Noun", ["time"], "", "", "SUOBI20", "", ""],
  ["시작", "start", "Noun", ["time", "event"], "", "", "SUOBI20", "", ""],
  ["학기 중", "during semester", "Noun", ["time"], "", "", "SUOBI20", "", ""],
  ["방학이 끝나다", "vacation is over", "Action Verb", ["intransitive_general"], "", "regular", "SUOBI20", "", ""],
  ["방학이 시작되다", "vacation starts", "Action Verb", ["intransitive_general"], "", "regular", "SUOBI20", "", ""],
  ["학기가 끝나다", "semester is over", "Action Verb", ["intransitive_general"], "", "regular", "SUOBI20", "", ""],
  ["학기가 시작되다", "semester starts", "Action Verb", ["intransitive_general"], "", "regular", "SUOBI20", "", ""],
  ["떡국", "tteokguk", "Noun", ["food"], "", "", "SUOBI20", "", ""],
  ["설날", "New Year's day", "Noun", ["time", "event"], "", "", "SUOBI20", "", ""],
  ["세배하다", "to do New Year's bow", "Action Verb", ["intransitive_general"], "", "hada", "SUOBI20", "", ""],
  ["어린이날", "Children's day", "Noun", ["time", "event"], "", "", "SUOBI20", "", ""],
  ["음력", "lunar calendar", "Noun", ["attribute"], "", "", "SUOBI20", "", ""],
  ["크리스마스트리", "Christmas tree", "Noun", ["object"], "", "", "SUOBI20", "", ""],
  ["한글날", "Hangul Proclamation day", "Noun", ["time", "event"], "", "", "SUOBI20", "", ""],
  ["휴가", "vacation", "Noun", ["time", "event"], "", "", "SUOBI20", "", ""],
  ["휴일", "holiday", "Noun", ["time", "event"], "", "", "SUOBI20", "", ""]

];

// Navigate to language units in the cache with `cache[partsOfSpeech][tag]`, or `cache[source]._all`
const cache = {};

function addLearningUnit(unit) {
  // If the unit isn't in the main array, add it (useful for runtime additions)
  if (!KR_EN_languageUnits.includes(unit)) {
    KR_EN_languageUnits.push(unit);
  }

  const pos = unit[DATA_SCHEMA.PartofSpeech];
  const src = unit[DATA_SCHEMA.Source];
  const tags = unit[DATA_SCHEMA.SemanticTags] || [];

  if (!cache[pos]) {
    cache[pos] = { _all: [] };
  }
  if (!cache[src]) {
    cache[src] = { _all: [] };
  }

  cache[pos]._all.push(unit);
  cache[src]._all.push(unit);

  tags.forEach(tag => {
    if (!cache[pos][tag]) {
      cache[pos][tag] = [];
    }
    cache[pos][tag].push(unit);
  });
}

function rebuildCache() {
  for (let key in cache) delete cache[key];
  KR_EN_languageUnits.forEach(unit => addLearningUnit(unit));
}

// Build the initial cache from the hardcoded array
rebuildCache();

function getWords(pos, requiredTag = null) {
  if (!cache[pos]) return [];
  if (!requiredTag) return cache[pos]._all || [];
  return cache[pos][requiredTag] || [];
}

function getPartOfSpeechCached(tagName) {
  let partsOfSpeech = [];
  for (const [key, value] of Object.entries(cache)) {
    if (value[tagName]) { partsOfSpeech.push(key); }
  }
  return partsOfSpeech;
}

module.exports = { KR_EN_languageUnits, addLearningUnit, getWords, rebuildCache, getPartOfSpeechCached, cache, DATA_SCHEMA };
